// src/tests/core/handlers/playerTurnHandler.assertTurnActiveFor.wrongActor.test.js
// --- FILE START ---

import {jest, describe, it, expect, beforeEach, afterEach} from '@jest/globals';

// --- Module to Test ---
// Adjust the path according to your project structure
import PlayerTurnHandler from '../../../core/handlers/playerTurnHandler.js';

// --- Mock Dependencies ---
// (Existing mocks remain the same)
const mockLogger = {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    debug: jest.fn(),
};
const mockActionDiscoverySystem = {
    getValidActions: jest.fn(),
};
const mockCommandProcessor = {
    processCommand: jest.fn(),
};
const mockWorldContext = {
    getLocationOfEntity: jest.fn(),
};
const mockEntityManager = {
    getEntityInstance: jest.fn(),
};
const mockGameDataRepository = {
    getActionDefinition: jest.fn(),
};
const mockPromptOutputPort = {
    prompt: jest.fn(),
};
const mockTurnEndPort = {
    notifyTurnEnded: jest.fn(),
};
// <<< ADDED Mock for CommandInputPort >>>
const mockUnsubscribeFn = jest.fn();
const mockCommandInputPort = {
    onCommand: jest.fn(() => mockUnsubscribeFn), // Needed for startTurn
};
// <<< END ADDED Mock >>>
const mockPlayerPromptService = {
    prompt: jest.fn(),
};
const mockCommandOutcomeInterpreter = {
    interpret: jest.fn(),
};
const mockSafeEventDispatcher = {
    dispatchSafely: jest.fn(),
};

// --- Test Suite ---
describe('PlayerTurnHandler: #_assertTurnActiveFor - Failure: Wrong Actor (Tested via _handleTurnEnd)', () => {
    /** @type {PlayerTurnHandler} */
    let handler;
    const className = PlayerTurnHandler.name; // Get class name for error messages
    const actualActorId = 'player-actual';
    const wrongActorId = 'player-expected-but-wrong';
    const currentActor = {id: actualActorId}; // Define actor object

    beforeEach(async () => {
        // Reset all mocks before each test run
        jest.clearAllMocks();
        // <<< Reset added mocks >>>
        mockUnsubscribeFn.mockClear();
        mockCommandInputPort.onCommand.mockClear();

        // Instantiate the handler with all mocks
        handler = new PlayerTurnHandler({
            logger: mockLogger,
            actionDiscoverySystem: mockActionDiscoverySystem,
            commandProcessor: mockCommandProcessor,
            worldContext: mockWorldContext,
            entityManager: mockEntityManager,
            gameDataRepository: mockGameDataRepository,
            promptOutputPort: mockPromptOutputPort,
            turnEndPort: mockTurnEndPort,
            commandInputPort: mockCommandInputPort, // <<< ADDED Dependency
            playerPromptService: mockPlayerPromptService,
            commandOutcomeInterpreter: mockCommandOutcomeInterpreter,
            safeEventDispatcher: mockSafeEventDispatcher,
        });

        // --- Setup ---
        // Configure PlayerPromptService.prompt to resolve immediately
        mockPlayerPromptService.prompt.mockResolvedValue();
        // Configure TurnEndPort to resolve if called (though it shouldn't be in this test)
        mockTurnEndPort.notifyTurnEnded.mockResolvedValue();


        // Start the turn for the 'actual' actor and wait for initiation
        await handler.startTurn(currentActor);

        // Allow any microtasks initiated by startTurn to settle.
        await new Promise(process.nextTick);

        // Clear any logs generated during setup (like startTurn starting)
        // to focus only on logs generated by the test step.
        jest.clearAllMocks();
        // Re-clear command mocks after setup clear
        mockUnsubscribeFn.mockClear();
        mockCommandInputPort.onCommand.mockClear();
    });

    afterEach(async () => { // Make afterEach async if destroy might be
        // Cleanup the handler instance
        if (handler) {
            try {
                // Destroy might trigger _handleTurnEnd if state wasn't perfectly cleaned,
                handler.destroy();
                await new Promise(process.nextTick); // Allow potential async in destroy
            } catch (e) {
                // Suppress errors during cleanup
                // console.error("Error during handler.destroy() in afterEach:", e);
            } finally {
                handler = null;
            }
        }
    });

    it('should log warning (from _handleTurnEnd guard) and attempt unsubscribe when _handleTurnEnd is called with the wrong actor ID', async () => { // Updated description
        // Define expected messages based on current implementation
        const expectedAssertionErrorMessage = `${className}: Assertion Failed - Turn is not active for the correct actor. Expected '${wrongActorId}' but current actor is '${actualActorId}'.`;
        const expectedWarningMessage = `${className}: _handleTurnEnd called for ${wrongActorId} (status: success), but assertion failed. Turn may have already ended or belongs to another handler/actor. Aborting end sequence. Error: ${expectedAssertionErrorMessage}`;


        // --- Steps ---
        // Call _handleTurnEnd with the wrong actor ID while the actual actor's turn is active.
        // This should trigger the internal #_assertTurnActiveFor, which throws.
        // The error should be caught by the try...catch within _handleTurnEnd.
        await handler._handleTurnEnd(wrongActorId, null); // Pass null error = success status

        // --- Assertions ---

        // 1. No Error Thrown Upwards: (Implicitly tested by test not crashing)

        // 2. Warning Logging (from _handleTurnEnd catch block):
        expect(mockLogger.warn).toHaveBeenCalledTimes(1);
        expect(mockLogger.warn).toHaveBeenCalledWith(expectedWarningMessage);

        // 3. No Port Call:
        expect(mockTurnEndPort.notifyTurnEnded).not.toHaveBeenCalled();

        // 4. Attempt Unsubscribe:
        // _handleTurnEnd's catch block calls _unsubscribeFromCommands. Since startTurn *was* called,
        // #commandUnsubscribeFn exists, and the actual unsubscribe function should be called.
        expect(mockUnsubscribeFn).toHaveBeenCalledTimes(1);
        expect(mockLogger.debug).toHaveBeenCalledWith(expect.stringContaining('Unsubscribing from command input'));

        // 5. No State Cleanup Attempt or further processing within _handleTurnEnd:
        expect(mockLogger.info).not.toHaveBeenCalledWith(expect.stringContaining(`Ending turn for actor ${wrongActorId}`));
        expect(mockLogger.debug).not.toHaveBeenCalledWith(expect.stringContaining(`Notifying TurnEndPort for actor ${wrongActorId}`));
        expect(mockLogger.debug).not.toHaveBeenCalledWith(expect.stringContaining(`Cleaning up active turn state for ${actualActorId}`));
        expect(mockLogger.debug).not.toHaveBeenCalledWith(expect.stringContaining(`_handleTurnEnd sequence completed for ${wrongActorId}`));

        // 6. No Other Logs:
        expect(mockLogger.error).not.toHaveBeenCalled();
        expect(mockLogger.info).not.toHaveBeenCalled(); // No 'Ending turn...' expected

    });
});

// --- FILE END ---