// src/tests/core/handlers/playerTurnHandler.assertTurnActiveFor.wrongActor.test.js
// --- FILE START ---

import {jest, describe, it, expect, beforeEach, afterEach} from '@jest/globals';

// --- Module to Test ---
// Adjust the path according to your project structure
import PlayerTurnHandler from '../../../core/handlers/playerTurnHandler.js';

// --- Mock Dependencies ---
// (Existing mocks remain the same)
const mockLogger = {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    debug: jest.fn(),
};
const mockActionDiscoverySystem = {
    getValidActions: jest.fn(),
};
const mockCommandProcessor = {
    processCommand: jest.fn(),
};
const mockWorldContext = {
    getLocationOfEntity: jest.fn(),
};
const mockEntityManager = {
    getEntityInstance: jest.fn(),
};
const mockGameDataRepository = {
    getActionDefinition: jest.fn(),
};
const mockPromptOutputPort = {
    prompt: jest.fn(),
};
const mockTurnEndPort = {
    notifyTurnEnded: jest.fn(),
};
// <<< ADDED Mock for CommandInputPort >>>
const mockUnsubscribeFn = jest.fn();
const mockCommandInputPort = {
    onCommand: jest.fn(() => mockUnsubscribeFn), // Needed for startTurn
};
// <<< END ADDED Mock >>>
const mockPlayerPromptService = {
    prompt: jest.fn(),
};
const mockCommandOutcomeInterpreter = {
    interpret: jest.fn(),
};
const mockSafeEventDispatcher = {
    dispatchSafely: jest.fn(),
    subscribe: jest.fn(),      // <<< CORRECTED: Added subscribe mock method
};

// --- Test Suite ---
describe('PlayerTurnHandler: #_assertTurnActiveFor - Failure: Wrong Actor (Tested via _handleTurnEnd)', () => {
    /** @type {PlayerTurnHandler} */
    let handler;
    const className = PlayerTurnHandler.name; // Get class name for error messages
    const actualActorId = 'player-actual';
    const wrongActorId = 'player-expected-but-wrong';
    const currentActor = {id: actualActorId}; // Define actor object

    beforeEach(async () => {
        // Reset all mocks before each test run
        jest.clearAllMocks();
        // <<< Reset added mocks >>>
        mockUnsubscribeFn.mockClear();
        mockCommandInputPort.onCommand.mockClear();

        // Instantiate the handler with all mocks
        handler = new PlayerTurnHandler({
            logger: mockLogger,
            actionDiscoverySystem: mockActionDiscoverySystem,
            commandProcessor: mockCommandProcessor,
            worldContext: mockWorldContext,
            entityManager: mockEntityManager,
            gameDataRepository: mockGameDataRepository,
            promptOutputPort: mockPromptOutputPort,
            turnEndPort: mockTurnEndPort,
            commandInputPort: mockCommandInputPort, // <<< ADDED Dependency
            playerPromptService: mockPlayerPromptService,
            commandOutcomeInterpreter: mockCommandOutcomeInterpreter,
            safeEventDispatcher: mockSafeEventDispatcher,
        });

        // --- Setup ---
        // Configure PlayerPromptService.prompt to resolve immediately
        mockPlayerPromptService.prompt.mockResolvedValue();
        // Configure TurnEndPort to resolve if called (though it shouldn't be in this test)
        mockTurnEndPort.notifyTurnEnded.mockResolvedValue();


        // Start the turn for the 'actual' actor and wait for initiation
        await handler.startTurn(currentActor);

        // Allow any microtasks initiated by startTurn to settle.
        await new Promise(process.nextTick);

        // Clear any logs generated during setup (like startTurn starting)
        // to focus only on logs generated by the test step.
        // Note: constructor log will still be in mockLogger.debug.mock.calls unless cleared explicitly
        // For this test, we will clear all logger mocks again to be very specific.
        mockLogger.info.mockClear();
        mockLogger.warn.mockClear();
        mockLogger.error.mockClear();
        mockLogger.debug.mockClear();

        // Mocks related to startTurn that might be called again (or checked)
        mockUnsubscribeFn.mockClear(); // This is important if we count its calls later
        // mockCommandInputPort.onCommand is likely only called once in startTurn anyway
    });

    afterEach(async () => { // Make afterEach async if destroy might be
        // Cleanup the handler instance
        if (handler) {
            try {
                handler.destroy();
                await new Promise(process.nextTick); // Allow potential async in destroy
            } catch (e) {
                // Suppress errors during cleanup
            } finally {
                handler = null;
            }
        }
    });

    it('should log warning (from _handleTurnEnd guard) and attempt unsubscribe when _handleTurnEnd is called with the wrong actor ID', async () => {
        // --- UPDATED Expected Warning Message ---
        const expectedWarningMessage = `${className}: _handleTurnEnd called for ${wrongActorId} (status: success), but this actor is not the current active actor (${actualActorId}) nor explicitly awaited. Turn may have already ended or belongs to a different context. Minimal cleanup attempted.`;


        // --- Steps ---
        // Call _handleTurnEnd with the wrong actor ID while the actual actor's turn is active.
        await handler._handleTurnEnd(wrongActorId, null); // Pass null error = success status

        // --- Assertions ---

        // 1. No Error Thrown Upwards: (Implicitly tested by test not crashing)

        // 2. Warning Logging (from _handleTurnEnd guard):
        expect(mockLogger.warn).toHaveBeenCalledTimes(1);
        expect(mockLogger.warn).toHaveBeenCalledWith(expectedWarningMessage);

        // 3. No Port Call:
        expect(mockTurnEndPort.notifyTurnEnded).not.toHaveBeenCalled();

        // 4. Attempt Unsubscribe:
        expect(mockUnsubscribeFn).toHaveBeenCalledTimes(1);

        // Verify the debug log from _unsubscribeFromCommands
        // --- UPDATED Debug Log Expectation ---
        // The actorContext in the log will be `this.#currentActor.id` (actualActorId)
        // because _handleTurnEnd calls #_unsubscribeFromCommands *after* the guard condition,
        // and #currentActor is still actualActorId.
        expect(mockLogger.debug).toHaveBeenCalledWith(
            `${className}: Unsubscribing from command input for actor context '${actualActorId}'.`
        );
        // Ensure it was the only debug log after clearing
        expect(mockLogger.debug).toHaveBeenCalledTimes(1);


        // 5. No State Cleanup Attempt for wrongActorId or further processing within _handleTurnEnd for wrongActorId:
        expect(mockLogger.info).not.toHaveBeenCalledWith(expect.stringContaining(`Ending turn for actor ${wrongActorId}`));

        // Check specific debug logs that should NOT have happened related to wrongActorId processing
        const wrongActorDebugLogs = [
            `Notifying TurnEndPort for actor ${wrongActorId}`,
            `Cleaning up active turn state for ${wrongActorId}`, // or primary
            `_handleTurnEnd sequence completed for ${wrongActorId}`
        ];
        mockLogger.debug.mock.calls.forEach(call => {
            wrongActorDebugLogs.forEach(phrase => {
                expect(call[0]).not.toContain(phrase);
            });
        });

        // It SHOULD NOT clean up state for actualActorId in THIS SPECIFIC CALL to _handleTurnEnd(wrongActorId, ...)
        expect(mockLogger.debug).not.toHaveBeenCalledWith(expect.stringContaining(`Cleaning up primary active turn state for ${actualActorId}`));


        // 6. No Other Critical Logs (like error, or info unrelated to startTurn which was cleared)
        expect(mockLogger.error).not.toHaveBeenCalled();
        // Check that no 'Ending turn for actor actualActorId' log was made during this specific call.
        const infoCalls = mockLogger.info.mock.calls;
        const endingTurnForActualActorLog = infoCalls.some(call => call[0].includes(`Ending turn for actor ${actualActorId}`));
        expect(endingTurnForActualActorLog).toBe(false);
        expect(mockLogger.info).toHaveBeenCalledTimes(0); // Should be no info logs after clearing

    });
});

// --- FILE END ---