/** @typedef {import('../../actions/actionTypes.js').ParsedCommand} ParsedCommand */

/**
 * @interface ICommandParser
 * @description Defines the contract for parsing raw command strings into structured commands.
 */
export class ICommandParser {
    /**
     * Parses a raw command string entered by the user or generated by the system.
     * @function parse
     * @param {string} commandString - The raw command text.
     * @returns {ParsedCommand} A structured representation of the command, including action ID,
     * targets, and any parsing errors.
     * @throws {Error} Implementations might throw errors for unrecoverable parsing issues,
     * though returning an error within ParsedCommand is preferred.
     */
    parse(commandString) {
        throw new Error('ICommandParser.parse method not implemented.');
    }
}