import { freeze } from '../../utils/cloneUtils.js';

/**
 * @file Core DI tokens excluding UI and AI groups.
 * @typedef {string} DiToken
 */

/**
 * Core application tokens.
 *
 * Dependency Injection Tokens
 *
 * Tokens for operation handlers follow the pattern:
 * [OperationName]Handler: '[OperationName]Handler'
 *
 * Naming conventions:
 * - Use PascalCase for operation name
 * - End with 'Handler'
 * - Do NOT use 'I' prefix for operation handlers (unlike other service interfaces)
 * - Example: DrinkFromHandler for DRINK_FROM operation (not IDrinkFromHandler)
 *
 * When adding a new operation handler token:
 * 1. Add token following the pattern above (without "I" prefix)
 * 2. Keep tokens alphabetically sorted within the operation handlers section
 * 3. Register handler in operationHandlerRegistrations.js
 * 4. Map operation in interpreterRegistrations.js
 *
 * @see src/dependencyInjection/registrations/operationHandlerRegistrations.js
 * @see src/dependencyInjection/registrations/interpreterRegistrations.js
 * @type {Readonly<Record<string, DiToken>>}
 */
export const coreTokens = freeze({
  IActionCategorizationService: 'IActionCategorizationService',
  ILogger: 'ILogger',
  ServiceSetup: 'ServiceSetup',
  AppContainer: 'AppContainer',
  EventBus: 'EventBus',
  IEventBus: 'IEventBus',
  IDataFetcher: 'IDataFetcher',
  ITextDataFetcher: 'ITextDataFetcher',
  IConfiguration: 'IConfiguration',
  IPathConfiguration: 'IPathConfiguration',
  ITraceConfiguration: 'ITraceConfiguration',
  ITraceConfigLoader: 'ITraceConfigLoader',
  IPathResolver: 'IPathResolver',
  ISchemaValidator: 'ISchemaValidator',
  IStringSimilarityCalculator: 'IStringSimilarityCalculator',
  IValidatorGenerator: 'IValidatorGenerator',
  IDataRegistry: 'IDataRegistry',
  ISpatialIndexManager: 'ISpatialIndexManager',
  ProxyUrl: 'ProxyUrl',
  SchemaLoader: 'SchemaLoader',
  RuleLoader: 'RuleLoader',
  ComponentLoader: 'ComponentLoader',
  ConditionLoader: 'ConditionLoader',
  ActionLoader: 'ActionLoader',
  EventLoader: 'EventLoader',
  MacroLoader: 'MacroLoader',
  LookupLoader: 'LookupLoader',
  EntityLoader: 'EntityLoader',
  EntityInstanceLoader: 'EntityInstanceLoader',
  WorldLoader: 'WorldLoader',
  GoalLoader: 'GoalLoader',
  ScopeLoader: 'ScopeLoader',
  TaskLoader: 'TaskLoader',
  RefinementMethodLoader: 'RefinementMethodLoader',
  ModsLoader: 'ModsLoader',
  GameConfigLoader: 'GameConfigLoader',
  PromptTextLoader: 'PromptTextLoader',
  LlmConfigLoader: 'LlmConfigLoader',
  ModManifestLoader: 'ModManifestLoader',
  ModDependencyValidator: 'ModDependencyValidator',
  ILoadCache: 'ILoadCache',
  AnatomyRecipeLoader: 'AnatomyRecipeLoader',
  AnatomyBlueprintLoader: 'AnatomyBlueprintLoader',
  AnatomyBlueprintPartLoader: 'AnatomyBlueprintPartLoader',
  AnatomySlotLibraryLoader: 'AnatomySlotLibraryLoader',
  AnatomyFormattingLoader: 'AnatomyFormattingLoader',
  AnatomyStructureTemplateLoader: 'AnatomyStructureTemplateLoader',
  GameDataRepository: 'GameDataRepository',
  EntityManager: 'EntityManager',
  SpatialIndexSynchronizer: 'SpatialIndexSynchronizer',
  JsonLogicEvaluationService: 'JsonLogicEvaluationService',
  JsonLogicCustomOperators: 'JsonLogicCustomOperators',
  ActionValidationContextBuilder: 'ActionValidationContextBuilder',
  PrerequisiteEvaluationService: 'PrerequisiteEvaluationService',
  TurnHandlerResolver: 'TurnHandlerResolver',
  ActorTurnHandler: 'ActorTurnHandler',
  PlaytimeTracker: 'PlaytimeTracker',
  ComponentCleaningService: 'ComponentCleaningService',
  SaveFileRepository: 'SaveFileRepository',
  SaveMetadataBuilder: 'SaveMetadataBuilder',
  ActiveModsManifestBuilder: 'ActiveModsManifestBuilder',
  GameStateCaptureService: 'GameStateCaptureService',
  ManualSaveCoordinator: 'ManualSaveCoordinator',
  GamePersistenceService: 'GamePersistenceService',
  EntityDisplayDataProvider: 'EntityDisplayDataProvider',
  AlertRouter: 'AlertRouter',
  ClosenessCircleService: 'ClosenessCircleService',
  LocationQueryService: 'LocationQueryService',
  EntityAccessService: 'EntityAccessService',
  ComponentAccessService: 'ComponentAccessService',
  LocationDisplayService: 'LocationDisplayService',
  GameSessionManager: 'GameSessionManager',
  PersistenceCoordinator: 'PersistenceCoordinator',
  BodyBlueprintFactory: 'BodyBlueprintFactory',
  GraphIntegrityValidator: 'GraphIntegrityValidator',
  BodyGraphService: 'BodyGraphService',
  AnatomyGenerationService: 'AnatomyGenerationService',
  AnatomyInitializationService: 'AnatomyInitializationService',
  ClothingInstantiationService: 'ClothingInstantiationService',
  ClothingInstantiationServiceV2: 'ClothingInstantiationServiceV2',
  ClothingManagementService: 'ClothingManagementService',
  ClothingAccessibilityService: 'ClothingAccessibilityService',
  EquipmentOrchestrator: 'EquipmentOrchestrator',
  LayerCompatibilityService: 'LayerCompatibilityService',
  ClothingSlotValidator: 'ClothingSlotValidator',
  SlotResolver: 'SlotResolver',
  IAnatomyBlueprintRepository: 'IAnatomyBlueprintRepository',
  IRecipeValidationRunner: 'IRecipeValidationRunner',
  IAnatomySocketIndex: 'IAnatomySocketIndex',
  IAnatomyCacheCoordinator: 'IAnatomyCacheCoordinator',
  IEntityMatcherService: 'IEntityMatcherService',
  IBlueprintProcessorService: 'IBlueprintProcessorService',
  AnatomyClothingCache: 'AnatomyClothingCache',
  LayerResolutionService: 'LayerResolutionService',
  DescriptorFormatter: 'DescriptorFormatter',
  BodyPartDescriptionBuilder: 'BodyPartDescriptionBuilder',
  BodyDescriptionComposer: 'BodyDescriptionComposer',
  AnatomyDescriptionService: 'AnatomyDescriptionService',
  AnatomyFormattingService: 'AnatomyFormattingService',
  EquipmentDescriptionService: 'EquipmentDescriptionService',
  ActivityDescriptionService: 'ActivityDescriptionService',
  RecipeProcessor: 'RecipeProcessor',
  PartSelectionService: 'PartSelectionService',
  SocketManager: 'SocketManager',
  ISocketGenerator: 'ISocketGenerator',
  ISlotGenerator: 'ISlotGenerator',
  IRecipePatternResolver: 'IRecipePatternResolver',
  EntityGraphBuilder: 'EntityGraphBuilder',
  RecipeConstraintEvaluator: 'RecipeConstraintEvaluator',
  PartDescriptionGenerator: 'PartDescriptionGenerator',
  BodyDescriptionOrchestrator: 'BodyDescriptionOrchestrator',
  DescriptionPersistenceService: 'DescriptionPersistenceService',
  AnatomyQueryCache: 'AnatomyQueryCache',
  EventDispatchService: 'EventDispatchService',
  ISafeEventDispatcher: 'ISafeEventDispatcher',
  IValidatedEventDispatcher: 'IValidatedEventDispatcher',
  IScopeRegistry: 'IScopeRegistry',
  IScopeEngine: 'IScopeEngine',
  IScopeDslErrorFactory: 'IScopeDslErrorFactory',
  IScopeDslErrorHandler: 'IScopeDslErrorHandler',
  IUnifiedScopeResolver: 'IUnifiedScopeResolver',
  IScopeCacheStrategy: 'IScopeCacheStrategy',
  IActionExecutor: 'IActionExecutor',
  IWorldContext: 'IWorldContext',
  ICommandProcessor: 'ICommandProcessor',
  IActionDiscoveryService: 'IActionDiscoveryService',
  ITargetResolutionService: 'ITargetResolutionService',
  ActionIndex: 'ActionIndex',
  ActionCandidateProcessor: 'ActionCandidateProcessor',
  ActionPipelineOrchestrator: 'ActionPipelineOrchestrator',
  IActionErrorContextBuilder: 'IActionErrorContextBuilder',
  IFixSuggestionEngine: 'IFixSuggestionEngine',
  ITargetComponentValidator: 'ITargetComponentValidator',
  ITargetRequiredComponentsValidator: 'ITargetRequiredComponentsValidator',
  IInputHandler: 'IInputHandler',
  ITurnOrderService: 'ITurnOrderService',
  ITurnManager: 'ITurnManager',
  ITurnContext: 'ITurnContext',
  IPromptOutputPort: 'IPromptOutputPort',
  ITurnEndPort: 'ITurnEndPort',
  IPromptCoordinator: 'IPromptCoordinator',
  ICommandOutcomeInterpreter: 'ICommandOutcomeInterpreter',
  IPlayerTurnEvents: 'IPlayerTurnEvents',
  IEntityManager: 'IEntityManager',
  IGameDataRepository: 'IGameDataRepository',
  ISaveFileRepository: 'ISaveFileRepository',
  ISaveLoadService: 'ISaveLoadService',
  IStorageProvider: 'IStorageProvider',
  IInitializationService: 'IInitializationService',
  assertValidEntity: 'assertValidEntity',
  ActionContextBuilder: 'ActionContextBuilder',
  TurnContextBuilder: 'TurnContextBuilder',
  WorldInitializer: 'WorldInitializer',
  SystemInitializer: 'SystemInitializer',
  ShutdownService: 'ShutdownService',
  GameLoop: 'GameLoop',
  OperationRegistry: 'OperationRegistry',
  OperationInterpreter: 'OperationInterpreter',
  SystemLogicInterpreter: 'SystemLogicInterpreter',
  DispatchEventHandler: 'DispatchEventHandler',
  DispatchSpeechHandler: 'DispatchSpeechHandler',
  DispatchThoughtHandler: 'DispatchThoughtHandler',
  DispatchPerceptibleEventHandler: 'DispatchPerceptibleEventHandler',
  LogHandler: 'LogHandler',
  LockMovementHandler: 'LockMovementHandler',
  LockMouthEngagementHandler: 'LockMouthEngagementHandler',
  ModifyComponentHandler: 'ModifyComponentHandler',
  AddComponentHandler: 'AddComponentHandler',
  RemoveComponentHandler: 'RemoveComponentHandler',
  QueryComponentHandler: 'QueryComponentHandler',
  QueryComponentsHandler: 'QueryComponentsHandler',
  QueryLookupHandler: 'QueryLookupHandler',
  SetVariableHandler: 'SetVariableHandler',
  EndTurnHandler: 'EndTurnHandler',
  ForEachHandler: 'ForEachHandler',
  SystemMoveEntityHandler: 'SystemMoveEntityHandler',
  IfHandler: 'IfHandler',
  IMoveEntityHandler: 'IMoveEntityHandler',
  GetTimestampHandler: 'GetTimestampHandler',
  GetNameHandler: 'GetNameHandler',
  RebuildLeaderListCacheHandler: 'RebuildLeaderListCacheHandler',
  CheckFollowCycleHandler: 'CheckFollowCycleHandler',
  EstablishFollowRelationHandler: 'EstablishFollowRelationHandler',
  BreakFollowRelationHandler: 'BreakFollowRelationHandler',
  AddPerceptionLogEntryHandler: 'AddPerceptionLogEntryHandler',
  QueryEntitiesHandler: 'QueryEntitiesHandler',
  HasComponentHandler: 'HasComponentHandler',
  ModifyArrayFieldHandler: 'ModifyArrayFieldHandler',
  ModifyContextArrayHandler: 'ModifyContextArrayHandler',
  IfCoLocatedHandler: 'IfCoLocatedHandler',
  MathHandler: 'MathHandler',
  RemoveFromClosenessCircleHandler: 'RemoveFromClosenessCircleHandler',
  EstablishSittingClosenessHandler: 'EstablishSittingClosenessHandler',
  EstablishLyingClosenessHandler: 'EstablishLyingClosenessHandler',
  RemoveSittingClosenessHandler: 'RemoveSittingClosenessHandler',
  RemoveLyingClosenessHandler: 'RemoveLyingClosenessHandler',
  BreakClosenessWithTargetHandler: 'BreakClosenessWithTargetHandler',
  AutoMoveFollowersHandler: 'AutoMoveFollowersHandler',
  AutoMoveClosenessPartnersHandler: 'AutoMoveClosenessPartnersHandler',
  MergeClosenessCircleHandler: 'MergeClosenessCircleHandler',
  HasBodyPartWithComponentValueHandler: 'HasBodyPartWithComponentValueHandler',
  UnequipClothingHandler: 'UnequipClothingHandler',
  UnlockMovementHandler: 'UnlockMovementHandler',
  UnlockMouthEngagementHandler: 'UnlockMouthEngagementHandler',
  RegenerateDescriptionHandler: 'RegenerateDescriptionHandler',
  ResolveDirectionHandler: 'ResolveDirectionHandler',
  AtomicModifyComponentHandler: 'AtomicModifyComponentHandler',
  SequenceHandler: 'SequenceHandler',
  TransferItemHandler: 'TransferItemHandler',
  ValidateInventoryCapacityHandler: 'ValidateInventoryCapacityHandler',
  DropItemAtLocationHandler: 'DropItemAtLocationHandler',
  PickUpItemFromLocationHandler: 'PickUpItemFromLocationHandler',
  OpenContainerHandler: 'OpenContainerHandler',
  TakeFromContainerHandler: 'TakeFromContainerHandler',
  PutInContainerHandler: 'PutInContainerHandler',
  ValidateContainerCapacityHandler: 'ValidateContainerCapacityHandler',
  DrinkFromHandler: 'DrinkFromHandler',
  DrinkEntirelyHandler: 'DrinkEntirelyHandler',
  TurnActionChoicePipeline: 'TurnActionChoicePipeline',
  ITurnDecisionProvider: 'ITurnDecisionProvider',
  IHumanDecisionProvider: 'IHumanDecisionProvider',
  IGoapDecisionProvider: 'IGoapDecisionProvider',
  ModLoadOrderResolver: 'ModLoadOrderResolver',
  ModManifestProcessor: 'ModManifestProcessor',
  ContentLoadManager: 'ContentLoadManager',
  WorldLoadSummaryLogger: 'WorldLoadSummaryLogger',
  SchemaPhase: 'SchemaPhase',
  GameConfigPhase: 'GameConfigPhase',
  ManifestPhase: 'ManifestPhase',
  ContentPhase: 'ContentPhase',
  AnatomyValidationPhase: 'AnatomyValidationPhase',
  WorldPhase: 'WorldPhase',
  SummaryPhase: 'SummaryPhase',
  BlueprintRecipeValidationRule: 'BlueprintRecipeValidationRule',
  ComponentExistenceValidationRule: 'ComponentExistenceValidationRule',
  PropertySchemaValidationRule: 'PropertySchemaValidationRule',
  ScopeEngine: 'ScopeEngine',
  DslParser: 'DslParser',
  TraceContextFactory: 'TraceContextFactory',
  CommandDispatcher: 'CommandDispatcher',
  DirectiveExecutor: 'DirectiveExecutor',
  ResultInterpreter: 'ResultInterpreter',
  UnifiedErrorHandler: 'UnifiedErrorHandler',
  DirectiveStrategyResolver: 'DirectiveStrategyResolver',
  // Character Builder Services
  ICharacterBuilderService: 'ICharacterBuilderService',
  CharacterBuilderService: 'CharacterBuilderService',
  DOMElementManager: 'DOMElementManager',
  EventListenerRegistry: 'EventListenerRegistry',
  ControllerLifecycleOrchestrator: 'ControllerLifecycleOrchestrator',
  ErrorHandlingStrategy: 'ErrorHandlingStrategy',
  AsyncUtilitiesToolkit: 'AsyncUtilitiesToolkit',
  PerformanceMonitor: 'PerformanceMonitor',
  ValidationService: 'ValidationService',
  MemoryManager: 'MemoryManager',
  ICharacterStorageService: 'ICharacterStorageService',
  CharacterStorageService: 'CharacterStorageService',
  IThematicDirectionGenerator: 'IThematicDirectionGenerator',
  ThematicDirectionGenerator: 'ThematicDirectionGenerator',
  ClicheGenerator: 'ClicheGenerator',
  ICoreMotivationsGenerator: 'ICoreMotivationsGenerator',
  CoreMotivationsGenerator: 'CoreMotivationsGenerator',
  CoreMotivationsDisplayEnhancer: 'CoreMotivationsDisplayEnhancer',
  TraitsGenerator: 'TraitsGenerator',
  TraitsDisplayEnhancer: 'TraitsDisplayEnhancer',
  SpeechPatternsGenerator: 'SpeechPatternsGenerator',
  SpeechPatternsDisplayEnhancer: 'SpeechPatternsDisplayEnhancer',
  SpeechPatternsResponseProcessor: 'SpeechPatternsResponseProcessor',
  CharacterDatabase: 'CharacterDatabase',
  // Traits Rewriter Services
  TraitsRewriterController: 'TraitsRewriterController',
  TraitsRewriterGenerator: 'TraitsRewriterGenerator',
  TraitsRewriterResponseProcessor: 'TraitsRewriterResponseProcessor',
  TraitsRewriterDisplayEnhancer: 'TraitsRewriterDisplayEnhancer',
  ICoreMotivationsCacheManager: 'ICoreMotivationsCacheManager',
  CoreMotivationsCacheManager: 'CoreMotivationsCacheManager',
  // Target Context Builder
  ITargetContextBuilder: 'ITargetContextBuilder',
  // Multi-Target Resolution Stage
  IMultiTargetResolutionStage: 'IMultiTargetResolutionStage',
  // Thematic Directions Manager Controller
  ThematicDirectionsManagerController: 'ThematicDirectionsManagerController',
  // Critical Log Notifier
  ICriticalLogNotifier: 'ICriticalLogNotifier',
  CriticalLogNotifier: 'CriticalLogNotifier',
  // Action Sequence Service
  ActionSequence: 'ActionSequence',
  // Mod Cross-Reference Validation
  IModReferenceExtractor: 'IModReferenceExtractor',
  IModCrossReferenceValidator: 'IModCrossReferenceValidator',
  IModValidationOrchestrator: 'IModValidationOrchestrator',
  IViolationReporter: 'IViolationReporter',
  // Unified Cache Infrastructure
  IUnifiedCache: 'IUnifiedCache',
  UnifiedCache: 'UnifiedCache',
  ICacheInvalidationManager: 'ICacheInvalidationManager',
  CacheInvalidationManager: 'CacheInvalidationManager',
  ICacheMetrics: 'ICacheMetrics',
  CacheMetrics: 'CacheMetrics',
  // Facade Infrastructure
  IFacadeFactory: 'IFacadeFactory',
  FacadeFactory: 'FacadeFactory',
  IFacadeRegistry: 'IFacadeRegistry',
  FacadeRegistry: 'FacadeRegistry',
  // System Facade Interfaces
  IClothingSystemFacade: 'IClothingSystemFacade',
  IAnatomySystemFacade: 'IAnatomySystemFacade',
  // Circuit Breaker (optional dependency for facades)
  ICircuitBreaker: 'ICircuitBreaker',
  // GOAP System Services
  IConditionalStepExecutor: 'IConditionalStepExecutor',
  IContextAssemblyService: 'IContextAssemblyService',
  IMethodSelectionService: 'IMethodSelectionService',
  IParameterResolutionService: 'IParameterResolutionService',
  IPlanningEffectsSimulator: 'IPlanningEffectsSimulator',
  IPrimitiveActionStepExecutor: 'IPrimitiveActionStepExecutor',
  IRefinementEngine: 'IRefinementEngine',
  IRefinementStateManager: 'IRefinementStateManager',
  // GOAP Heuristics (GOAPIMPL-017)
  IGoalDistanceHeuristic: 'IGoalDistanceHeuristic',
  IRelaxedPlanningGraphHeuristic: 'IRelaxedPlanningGraphHeuristic',
  IHeuristicRegistry: 'IHeuristicRegistry',
  // GOAP Planner (GOAPIMPL-018)
  IGoapPlanner: 'IGoapPlanner',
  // GOAP Task Library Constructor (GOAPIMPL-019)
  ITaskLibraryConstructor: 'ITaskLibraryConstructor',
  // GOAP Plan Invalidation Detector (GOAPIMPL-020)
  IPlanInvalidationDetector: 'IPlanInvalidationDetector',
  // GOAP Controller (GOAPIMPL-021)
  IGoapController: 'IGoapController',
  // GOAP Knowledge Manager (GOAPIMPL-023-02)
  IKnowledgeManager: 'IKnowledgeManager',
  // GOAP Debug Tools (GOAPIMPL-025-06)
  IPlanInspector: 'IPlanInspector',
  IStateDiffViewer: 'IStateDiffViewer',
  IRefinementTracer: 'IRefinementTracer',
  IGOAPDebugger: 'IGOAPDebugger',
  // GOAP Numeric Constraint Evaluator (MODCOMPLASUP-001)
  INumericConstraintEvaluator: 'INumericConstraintEvaluator',
});
