# GitHub Actions workflow for ActionDefinitionBuilder Quality Gates
name: ActionDefinitionBuilder Quality Gates

on:
  push:
    paths:
      - 'src/actions/builders/**'
      - 'tests/unit/actions/builders/**'
      - 'tests/integration/actions/actionDefinitionBuilder.integration.test.js'
      - 'tests/performance/actions/actionBuilderPerformance.test.js'
      - 'tests/common/actions/actionBuilderHelpers.js'
  pull_request:
    paths:
      - 'src/actions/builders/**'
      - 'tests/unit/actions/builders/**'
      - 'tests/integration/actions/actionDefinitionBuilder.integration.test.js'
      - 'tests/performance/actions/actionBuilderPerformance.test.js'
      - 'tests/common/actions/actionBuilderHelpers.js'

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run TypeScript check
      run: npm run typecheck
    
    - name: Run ActionDefinitionBuilder tests with coverage
      run: npm run test:actionbuilder
    
    - name: Run Quality Gates
      run: npm run quality:gates
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.node-version == '20.x'
      with:
        directory: ./coverage
        flags: actionbuilder
        name: actionbuilder-coverage
        fail_ci_if_error: true
    
    - name: Archive performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results-node-${{ matrix.node-version }}
        path: |
          coverage/
          performance-results.json
        retention-days: 30